name: Build and Deploy to Server

on:
  push:
    branches: [juy-testing]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: 15.235.185.253
          username: debian
          key: ${{ secrets.SSH_KEY_FRIGUS_ME }}
          passphrase: ${{ secrets.CICD_PASSPHRASE }}
          port: 22
          script: |
            pwd
            ls -l
